General EvalTool GPX update polish items.
inertialsense/inertial-sense-sdk pull request #490
Opened 2023-11-03 21:12 UTC by tmcd249

General EvalTool GPX update polish items.

2023-11-03 21:32 UTC, kylemallory requested changes

2023-11-03 21:32 UTC, kylemallory commented on src/ISFirmwareUpdater.cpp
> +    printf("Requested Firmware Update to device '%s' with Image '%s', md5: %08x-%08x-%08x-%08x\n%s\n", fwUpdate_getSessionTargetName(), filename.c_str(), session_md5[0], session_md5[1], session_md5[2
We should revert this...  It doesn't gain us anything

2023-11-03 21:32 UTC, kylemallory commented on src/ISFirmwareUpdater.cpp
> +    if (hasPendingCommands())
While this is easier to read, it should probably just be a series of if ( () || () || () || () ) return false;

2023-11-03 21:32 UTC, kylemallory commented on src/InertialSense.cpp
> +            if (!fwUpdater->fwUpdate_isDone())
This two ifs should be combined: `if (fwUpdater != null && fwUpdate->fwUpdate_isDone()) return false;`

2023-11-03 21:32 UTC, kylemallory commented on src/InertialSense.cpp
> +            if (fwUpdater->hasPendingCommands() || ((fwUpdater->fwUpdate_getSessionStatus() >= fwUpdate::NOT_STARTED) && (fwUpdater->fwUpdate_getSessionStatus() < fwUpdate::FINISHED)))
This should also be updated to use `if (fwUpdater != null && !fwUpdate->fwUpdate_isDone()) return false;` and ensure we are using the same logic in all places.  Note this one is a NOT fwUpdate_isDone().

2023-11-03 22:19 UTC, kylemallory approved these changes

2023-11-04 22:13 UTC, waltjohnson approved these changes

2023-11-04 22:14 UTC, merged