initial stuff
inertialsense/inertial-sense-sdk pull request #544
Opened 2024-02-09 21:27 UTC by tmcd249

- (SDK) DID_NMEA_BCAST_PERIOD matches the ASCII message $ASCE instead of the deprecated $ASCB.

2024-02-09 21:59 UTC, waltjohnson approved these changes

2024-02-10 05:50 UTC, kylemallory approved these changes

2024-02-10 05:51 UTC, kylemallory requested changes
Looks good, but it also looks like it broke the unit-tests.  Definitely need to address that.

2024-02-12 19:44 UTC, kylemallory approved these changes

2024-02-12 19:44 UTC, merged