Sn 4993 did m pack
inertialsense/inertial-sense-sdk pull request #589
Opened 2024-03-29 20:17 UTC by tmcd249

Adds did for future mPack or wildcard messages.

2024-03-29 21:01 UTC, kylemallory requested changes
Good start! But lets drop the 'IS' from the code/classes/types/macros.

2024-03-29 21:09 UTC, tmcd249 commented on src/data_sets.h
> +    ISEventProtocol_EPH     = 250,
it was random and really should be removed for this PR

2024-03-29 21:10 UTC, tmcd249 commented on src/data_sets.h
> +    uint8_t         protocol;
just didnt see it getting that large but if we think it should be larger it can be

2024-04-02 20:04 UTC, kylemallory approved these changes
Looks great!

2024-04-03 03:48 UTC, waltjohnson approved these changes

2024-04-03 16:17 UTC, merged