Sn 5140 filter gsv
inertialsense/inertial-sense-sdk pull request #633
Opened 2024-05-29 23:52 UTC by tmcd249

NMEA protocol now supports filtering of GxGSV by constellation and frequency.

2024-05-30 18:55 UTC, waltjohnson approved these changes

2024-05-31 17:51 UTC, kylemallory requested changes

2024-05-31 18:15 UTC, tmcd249 commented on src/data_sets.h
> +#define NMEA_GNGSV_GPS_OFFSET    (SAT_SV_GNSS_ID_GPS << 4)
this is an offset of (CONST_ID << 4) + NMEA_MSG_ID_SPECIAL_CASE_START * BASE_MSG_NUM

2024-05-31 18:36 UTC, tmcd249 commented on src/protocol_nmea.cpp
> +    s_protocol_version = protocol_version;
I think these were added to work with the unit tests but honestly i don't know the reasoning

2024-05-31 21:01 UTC, tmcd249 commented on src/data_sets.h
> +#define NMEA_GNGSV_FREQ_5_BIT    (0x01 << 3)
There is no frequency 4 also. L3 is a Glonass, beidou and QZSS thing. 1,2,3,5 are the supported frequencys channels. L is only GPS and SBS.

2024-05-31 21:04 UTC, tmcd249 commented on src/protocol_nmea.cpp
> + * 	-2 for invalid length
fixed

2024-05-31 21:07 UTC, tmcd249 commented on src/protocol_nmea.cpp
> + * returns 15 if successful
fixed

2024-05-31 21:16 UTC, tmcd249 commented on src/protocol_nmea.cpp
> +    else if (a[1] == 'P')  msgNum = NMEA_GNGSV_START | NMEA_GNGSV_GPS_OFFSET;
it is and offset from the base number of NMEA_GNGSV_START. All GPS messages are offset 16 messages from their GNGSV counterpart. You are right about intialising. Adding that in.

2024-05-31 21:28 UTC, kylemallory commented on src/protocol_nmea.cpp
> +    else if (a[1] == 'P')  msgNum = NMEA_GNGSV_START | NMEA_GNGSV_GPS_OFFSET;
If it is an offset from GNGSV_START, then should it be msgNUm = NGMA_GNGSV_START + NMEA_GNGSV_x_OFFSET?   That would make more sense here.

2024-05-31 21:38 UTC, tmcd249 commented on src/protocol_nmea.cpp
> +}gsvMask_t;
agreed

2024-05-31 21:38 UTC, tmcd249 commented on src/protocol_nmea.cpp
> +    else if (a[1] == 'P')  msgNum = NMEA_GNGSV_START | NMEA_GNGSV_GPS_OFFSET;
Fixed

2024-05-31 22:40 UTC, kylemallory approved these changes

2024-06-01 07:13 UTC, merged