Switch evaltool to use ISDataMappings
inertialsense/inertial-sense-sdk pull request #694
Opened 2024-08-18 06:53 UTC by waltjohnson

2024-09-01 19:48 UTC, tmcd249 approved these changes

2024-09-05 04:20 UTC, kylemallory requested changes
Minor stuff...

2024-09-27 16:59 UTC, kylemallory requested changes
I think we should allocate some time to fix this right.  I know its not a "big priority" but in its current state, this appears only half-baked.  I think between you, Tony and I we could probably get this finished in about 30m to an hour, unless I'm missing some bigger issue.

2024-09-27 16:59 UTC, kylemallory commented on src/ISDataMappings.cpp
> +#if 0
This is a big block of dead code.  Do we need it?

2024-09-27 16:59 UTC, kylemallory commented on src/ISDataMappings.cpp
> +    ADD_MAP_7("activePorts", activePorts, DATA_TYPE_UINT8, uint8_t, "", "Number of active ports", DATA_FLAGS_READ_ONLY);
I thought you have changed these to the mapper.AddMember() template.  These appear to be arrays.  Are arrays not supported in the template?  I think I remember you saying something about that.

2024-10-02 23:59 UTC, merged