Code migration from ROS 1 to ROS 2.
inertialsense/inertial-sense-sdk pull request #698
Opened 2024-08-24 00:53 UTC by sbogdanov2

Converted ROS 1 syntax to ROS 2, including messages, console logs, and parameters. Also worked on ROS 2 bridge tests.

2024-08-26 22:51 UTC, kylemallory requested changes
Savva, this looks pretty good, but there are a lot of files that need to be removed from the PR, and deleted from the Git repo.

Also, we should look to see how we can consolidate the code that is shared/common/similar between ROS1 and ROS2.  Ideally, only changes that are unique to ROS2 should be here.

If necessary, we may want to try and back-port some of the ROS2 changes into ROS1, where possible, to make sure they play nice with both teams.  For example, I know there were some case-issues early on; can we use the ROS2 case-specific names, etc in ROS1?  There is probably some level of cross compatibility. If not, that is fine, but let's explore it.

2024-08-26 22:51 UTC, kylemallory commented on .gitignore
> +/ros2/log/
Should also add .ninja to the .gitnore, and while we're at it, remove the two .ninja files below.  They do not belong in the PR/repo.

2024-08-26 22:51 UTC, kylemallory commented on .ninja_deps
Remove this.

2024-08-26 22:51 UTC, kylemallory commented on .ninja_log
Remove this.

2024-08-26 22:51 UTC, kylemallory commented on Testing/Temporary/LastTest.log
These should be removed as well.

2024-08-26 22:51 UTC, kylemallory commented on build.ninja
Do we need this file too? This says its generated, in which case we should not need to keep it.  Ie, ANY generated files should not be committed (should be added to .gitignore), since they will just be regenerated with each build.

Is ninja a requirement for ROS only, or did these come from somewhere else, like the IDE?  If so required for ROS, we should probably move it into the ROS2 folder.  Otherwise, let's discuss.

2024-08-26 22:51 UTC, kylemallory commented on ros2/File.txt
Remove

2024-08-26 22:51 UTC, kylemallory commented on ros2/File_errors1.txt
Remove all of these File_errors*.txt

2024-08-26 22:51 UTC, kylemallory commented on ros2/include/ParamHelper.h
A lot of these files are copied from the ROS1 code.  How much has changed between them, for the conversion to ROS2?  If its significant, we can keep them.  If its minor, or not at all, we should look at organizing them so they can be shared between both versions.

The thing we ultimately want to avoid is having to make identical changes in both, whenever we fix something in the future that applies to both.  So, let's do an IDE comparison between this new file and the original ROS1 version, and see what the correct course of action here should be.

2024-09-18 16:48 UTC, kylemallory reviewed
This is a good start to consolidating common code elements, by moving shared code out into ROS/include.  We should also have a ROS/src, where common source is included (things like ParamHelper.cpp, etc).

2024-09-18 16:48 UTC, kylemallory commented on ROS/include/RtkBase.h
> +#endif
Use an #elif defined(ROS1) or just an #else to catch the "ROS1" version below.

2024-09-18 16:48 UTC, kylemallory commented on ROS/include/RtkBase.h
> +#ifdef ROS2
Is there no ROS1 equivelant nh_?

2024-09-18 16:48 UTC, kylemallory commented on .cmake/api/v1/query/cache-v2
I see that .cmake is already in the .gitignore, but we still have these files being added in the PR.  They need to be removed/deleted from your branch and pushed up.  You will probably need to remove `.cmake/` from the .gitignore, then delete and push the deletes up, then add `.cmake/` back into .gitignore, and then finally commit/push .gitignore to the repo.

2024-09-18 16:48 UTC, kylemallory commented on ROS/ros/include/TopicHelper.h
Looks like this is included twice still, but identical in both locations.

2024-09-18 16:48 UTC, kylemallory commented on ROS/ros/include/ParamHelper.h
Looks like this should be in ROS/include, rather than ROS/ros/include.  Also, if possible, lets rename ROS/ros to ROS/ros1 so that its clear this is the ROS1-specific code.

2024-09-25 18:10 UTC, waltjohnson approved these changes

2024-09-27 16:43 UTC, kylemallory approved these changes

2024-09-27 17:07 UTC, tmcd249 approved these changes

2024-10-06 23:47 UTC, merged