initial
inertialsense/inertial-sense-sdk pull request #701
Opened 2024-08-25 17:50 UTC by tmcd249

(SDK) NMEA GxGSV references changed to GNGSV.

2024-08-27 19:02 UTC, kylemallory commented on src/protocol_nmea.cpp
> +    if(a[1] == 'x' || a[1] == 'X')        return NMEA_MSG_ID_GNGSV;
Is this still appropriate?  Below, on 1787, we also have a GxVTG, that won't be parsed if this line remains.  Should that GxVTG also be updated to be GNVTG?

2024-09-06 02:37 UTC, kylemallory approved these changes

2024-09-09 20:53 UTC, waltjohnson requested changes

2024-09-09 20:53 UTC, waltjohnson commented on src/data_sets.h
>      NMEA_MSG_ID_GxVTG     = 16,
@tmcd249  Let's rename these to "N" in eNmeaMsgId and call it a day:

```
    NMEA_MSG_ID_GNGGA     = 7,
    NMEA_MSG_ID_GNGLL     = 8,
    NMEA_MSG_ID_GNGSA     = 9,
    NMEA_MSG_ID_GNRMC     = 10,
    NMEA_MSG_ID_GNZDA     = 11,

    NMEA_MSG_ID_GNVTG     = 16,
```

2024-09-10 17:40 UTC, kylemallory approved these changes

2024-09-10 23:12 UTC, waltjohnson approved these changes

2024-09-11 16:09 UTC, merged