Sn 5388 gps quick bit
inertialsense/inertial-sense-sdk pull request #727
Opened 2024-10-07 21:10 UTC by tmcd249

(GPX) GPX performs GNSS hardware status checks and reports via DID_GPX_STATUS under 'hdwStatus'. (PR-977)

2024-10-09 16:45 UTC, kylemallory requested changes
Can you include screenshots of the new logInspector plots?  The code looks good, but I'd like to verify the UI and provide feedback on it if needed.  Otherwise, this looks good.

2024-10-09 19:18 UTC, waltjohnson commented on src/data_sets.h
> +    /** GPS signal error mask*/
Can you give more description or cause for this CN0 error?

2024-10-09 20:23 UTC, waltjohnson approved these changes

2024-10-11 21:46 UTC, kylemallory approved these changes

2024-10-12 02:26 UTC, merged